# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mãos à obra
email: gustavolop@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programação, música, atualidades e sugestões para a vida
  seguir ou não, cabe a cada um
  entre e sinta-se em casa! :)
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://gustavohsl.github.io" # the base hostname & protocol for your site
twitter_username: gustavohsl
github_username:  GustavoHSL

# Build settings
markdown: kramdown
timezone: America/Sao_Paulo